link : list item_car main auto
	gcc auto.o list.o item_car.o main.o -Wall -Wextra

auto :
	gcc -c auto.c -Wall -Wextra

item_car :
	gcc -c item_car.c -Wall -Wextra

list :
	gcc -c list.c -Wall -Wextra

main : 
	gcc -c main.c -Wall -Wextra

clean : 
	rm -f *.o *.out

